version: "3"
services:
  web:
    image: leoknight/node-demo:0.2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "5555:3000"
    networks:
      - webnet
networks:
  webnet: