version: "3"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
    expose:
      - "3000"
    command: "npm start"