version: '3'
networks:
  my-net:

services:

  web:
    build: .
    ports:
     - "3000:3000"
    networks: 
     - my-net
    # links:
    #  - mongo
     
  mongo:
    image: "mongo"
    networks: 
     - my-net